# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "limina-buy-orders"
client_id = "your-client-id-here"
application_url = "https://your-ngrok-url.ngrok.io"
embedded = true

[access_scopes]
# Scopes needed for the app to function
scopes = "write_products,read_products,write_orders,read_orders,write_customers,read_customers"

[auth]
redirect_urls = [
  "https://your-ngrok-url.ngrok.io/auth/callback",
  "https://your-ngrok-url.ngrok.io/auth/shopify/callback",
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "https://limina-test.myshopify.com"
include_config_on_deploy = true

[app_proxy]
url = "https://your-ngrok-url.ngrok.io/app_proxy"
subpath = "limina"
prefix = "apps"