name: HTML Lint

on:
  pull_request:
  push:
    branches: [main]

jobs:
  html-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install htmlhint
        run: npm install -g htmlhint
      - name: Run htmlhint
        run: htmlhint '**/*.html'
